In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import glob
import os
import gc
import pyarrow
import pyarrow.parquet
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
from datetime import timedelta
from pandas import ExcelWriter
from google.cloud import bigquery
from itertools import combinations, permutations

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth",0)
pd.options.display.float_format = '{:,}'.format
import calendar

from dateutil.relativedelta import relativedelta
import io


from google.cloud import bigquery
from google.cloud import storage
#import pyodbc
import re



import pandas as pd
from sklearn.preprocessing import OneHotEncoder

import pandas as pd
from datetime import timedelta

from sklearn.feature_extraction.text import TfidfVectorizer


import traceback
import string
from pandas.tseries.offsets import DateOffset
import os
from google.cloud import bigquery
from google.cloud import storage
#import pyodbc
import re
import pandas as pd
import numpy as np
import pandas.core.algorithms as algos
from pandas import Series




from sklearn.linear_model import LogisticRegression
from catboost import CatBoostClassifier,Pool
import optuna
from sklearn.model_selection import train_test_split,GridSearchCV,cross_val_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, roc_curve,confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Lasso
from sklearn.metrics import precision_recall_curve
import optuna
from sklearn.model_selection import train_test_split,GridSearchCV,RandomizedSearchCV

import seaborn as sns
import matplotlib.pyplot as plt
import pickle
from scipy.stats import chi2_contingency

In [2]:
%%bigquery planet_portfolio_penetration


WITH DIM_AGG AS (
    SELECT 
        b.AGREEMENTNO,
        a.CUSTOMERID,
        a.DOB,
        a.MOBILE,
        a.CITY,
        b.SOURCESYSTEMID,
        b.LOANSTATUS,
        b.STATE,
        b.DISBURSALDATE,
        b.DISBURSALAMOUNT,
        b.SCHEMENAME,
        b.PRODUCTNAME,
        a.UCID,
        b.PRODUCTID,
        b.NPASTAGEID
    FROM `edw-prod.DWH.LMS_DIMCUSTOMER` a
    LEFT JOIN (
        SELECT AGREEMENTNO, CUSTOMERID, SOURCESYSTEMID, LOANSTATUS, DISBURSALDATE, DISBURSALAMOUNT, SCHEMENAME, PRODUCTNAME, PRODUCTID, STATE, NPASTAGEID 
        FROM `edw-prod.DWH.LMSFR_DIMAGREEMENT`
        UNION ALL
        SELECT AGREEMENTNO, CUSTOMERID, SOURCESYSTEMID, LOANSTATUS, DISBURSALDATE, DISBURSALAMOUNT, SCHEMENAME, PRODUCTNAME, PRODUCTID, STATE, NPASTAGEID 
        FROM `edw-prod.DWH.LMS_DIMAGREEMENT`
        UNION ALL
        SELECT AGREEMENTNO, CUSTOMERID, SOURCESYSTEMID, LOANSTATUS, DISBURSALDATE, DISBURSALAMOUNT, SCHEMENAME, PRODUCTNAME, PRODUCTID, STATE, NPASTAGEID 
        FROM `edw-prod.DWH.LMSML_DIMAGREEMENT`
    ) b
    ON a.CUSTOMERID = b.CUSTOMERID
    WHERE b.AGREEMENTNO IS NOT NULL
    AND b.LOANSTATUS IN ('A', 'C', 'ACTIVE', 'CLOSED')
),

DIM_AGG_FINAL AS (
    SELECT *,
        CASE 
            WHEN SOURCESYSTEMID = 21 THEN "TW"
            WHEN SOURCESYSTEMID = 20 THEN "HL"
            WHEN SOURCESYSTEMID = 23 THEN "CL"
            WHEN SOURCESYSTEMID = 25 THEN "SME"
            WHEN SOURCESYSTEMID = 24 THEN "Farm"
            WHEN SOURCESYSTEMID = 27 THEN "WRF"
            WHEN SOURCESYSTEMID = 15 THEN "ML"
            WHEN SOURCESYSTEMID = 1 THEN "Farm"
            WHEN SOURCESYSTEMID = 6 THEN "Wholesale"
            WHEN SOURCESYSTEMID = 26 THEN "Rural-LAP"
            ELSE "Non-LTF"
        END AS PRODUCT,
        CASE 
            WHEN SCHEMENAME = "SUFIN" THEN "Supply-Chain-Finance"
            WHEN LOWER(PRODUCTNAME) LIKE '%lap%' OR LOWER(PRODUCTNAME) LIKE '%loan against property%' AND SOURCESYSTEMID = 20 THEN "Loan-Against-Property"
            ELSE CASE 
                WHEN SOURCESYSTEMID = 21 THEN "TW"
                WHEN SOURCESYSTEMID = 20 THEN "HL"
                WHEN SOURCESYSTEMID = 23 THEN "CL"
                WHEN SOURCESYSTEMID = 25 THEN "SME"
                WHEN SOURCESYSTEMID = 24 THEN "Farm"
                WHEN SOURCESYSTEMID = 27 THEN "WRF"
                WHEN SOURCESYSTEMID = 15 THEN "ML"
                WHEN SOURCESYSTEMID = 1 THEN "Farm"
                WHEN SOURCESYSTEMID = 6 THEN "Wholesale"
                WHEN SOURCESYSTEMID = 26 THEN "Rural-LAP"
                ELSE "Non-LTF"
            END
        END AS Product_Final
    FROM DIM_AGG
),

DIM_AGG_CHECK AS (
    SELECT * FROM DIM_AGG_FINAL
    WHERE MOBILE IS NOT NULL AND MOBILE != 'None'
),

DIM_AGG_CHECK_FINAL AS (
    SELECT * FROM (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY UCID, Product_Final ORDER BY DISBURSALDATE DESC) AS rn
        FROM DIM_AGG_CHECK
        WHERE UCID IS NOT NULL
    ) WHERE rn = 1
),

PRODUCT_DIST_FINAL AS (
    SELECT 
        Product_Final, 
        CASE 
            WHEN Product_Final IN ('ML','TW') AND NPASTAGEID = 'WRITEOFF' THEN 'WRITEOFF'
            WHEN Product_Final IN ('ML','TW') THEN LOANSTATUS
            ELSE LOANSTATUS 
        END AS Final_Status, 
        COUNT(DISTINCT UCID) AS unique_agreement_count,
        'PRODUCT' AS Source_Tag  
    FROM DIM_AGG_CHECK_FINAL
    GROUP BY Product_Final, Final_Status
),

PLANET_REG AS (
    SELECT USER_PHNO1 AS MOBILE, USER_ID, CREATE_TS AS Planet_Reg_Date
  FROM `dataeng-datalake-prod.D2C.TB_ASMI_USER`
  UNION ALL
  SELECT USER_PHNO1 AS MOBILE, USER_ID,CREATE_TS AS Planet_Reg_Date
  FROM `edw-prod.DWH_MART.D2C_TB_ASMI_USER`
),

PLANET_AGG AS (
    SELECT 
        p.MOBILE AS MOBILE_ASMI, 
        p.USER_ID, 
        p.Planet_Reg_Date, 
        d.AGREEMENTNO, 
        d.MOBILE, 
        d.UCID, 
        d.STATE, 
        d.LOANSTATUS, 
        d.PRODUCT, 
        d.Product_Final, 
        d.DISBURSALDATE, 
        d.NPASTAGEID
    FROM PLANET_REG p
    LEFT JOIN DIM_AGG_FINAL d
    ON p.MOBILE = d.MOBILE
),

PLANET_CHECK_FINAL AS (
    SELECT * FROM (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY UCID, Product_Final ORDER BY DISBURSALDATE DESC) AS rn
        FROM PLANET_AGG
        WHERE UCID IS NOT NULL
    ) WHERE rn = 1
),

PLANET_DIST_FINAL AS (
    SELECT 
        Product_Final, 
        CASE 
            WHEN Product_Final IN ('ML','TW') AND NPASTAGEID = 'WRITEOFF' THEN 'WRITEOFF'
            WHEN Product_Final IN ('ML','TW') THEN LOANSTATUS
            ELSE LOANSTATUS 
        END AS Final_Status, 
        COUNT(DISTINCT UCID) AS unique_ucid_count,
        'PLANET' AS Source_Tag  
    FROM PLANET_CHECK_FINAL
    GROUP BY Product_Final, Final_Status
)

SELECT * FROM PRODUCT_DIST_FINAL
UNION ALL
SELECT * FROM PLANET_DIST_FINAL;

Query is running:   0%|          |

Downloading:   0%|          |

In [4]:
planet_portfolio_penetration.pivot(
    index=[ 'Product_Final'],
    columns=['Source_Tag','Final_Status'],
    values='unique_agreement_count'
).fillna(0)

Source_Tag             PRODUCT                     PLANET
Final_Status                 C WRITEOFF        A        C        A WRITEOFF
Product_Final
CL                     470521   0        773476   330387   584560   0
Farm                   660145   0        463798   102225   172789   0
HL                     18911    0        45220    13509    37566    0
Loan-Against-Property  5484     0        11809    3650     9304     0
ML                     5630920  2997623  5614873  686489   813861   133252
Non-LTF                0        0        28       0        8        0
Rural-LAP              489      0        17547    277      5261     0
SME                    6379     0        46202    5037     33776    0
TW                     6103967  496417   2333552  2227825  1725389  91241
WRF                    339      0        193      230      104      0

# MAU

In [2]:
%%bigquery MAU_lob
WITH user_mapping AS (
  SELECT PHONE_NO AS planet_phone_no, USER_CREATION_ID AS USER_ID
  FROM `dataeng-datalake-prod.D2C.D2C_USER_REG_LOGIN`
  UNION ALL
  SELECT USER_PHNO1 AS planet_phone_no, USER_ID
  FROM `edw-prod.DWH_MART.D2C_TB_ASMI_USER`
),

loc_with_mobile AS (
  -- All login events with mobile mapping
  SELECT 
    l.USER_ID,
    l.CREATED_TS,
    m.planet_phone_no
  FROM (
    SELECT USER_ID, CREATED_TS
    FROM `edw-prod.DWH_MART.D2C_TB_USER_LOC_TRACKING`
    WHERE CREATED_TS >= '2025-01-01'
      AND CREATED_TS < '2026-06-01'
    
    UNION ALL
    
    SELECT USER_CREATION_ID AS USER_ID, LOGIN_DATE AS CREATED_TS
    FROM `dataeng-datalake-prod.D2C.D2C_USER_LOGIN_TRACKER`
    WHERE LOGIN_DATE >= '2025-01-01'
      AND LOGIN_DATE < '2026-06-01'
  ) l
  LEFT JOIN user_mapping m
    ON l.USER_ID = m.USER_ID
),

dim_agg AS (
  SELECT 
    b.AGREEMENTNO,
    a.CUSTOMERID,
    a.DOB,
    a.MOBILE,
    b.SOURCESYSTEMID,
    b.LOANSTATUS,
    b.SCHEMENAME,
    b.PRODUCTNAME,
    a.UCID,
    b.PRODUCTID
  FROM (
    SELECT CUSTOMERID, DOB, MOBILE, UCID
    FROM `edw-prod.DWH.LMS_DIMCUSTOMER`
  ) a
  LEFT JOIN (
    SELECT AGREEMENTNO, CUSTOMERID, SOURCESYSTEMID, LOANSTATUS, SCHEMENAME, PRODUCTNAME, PRODUCTID 
    FROM `edw-prod.DWH.LMSFR_DIMAGREEMENT`
    UNION ALL
    SELECT AGREEMENTNO, CUSTOMERID, SOURCESYSTEMID, LOANSTATUS, SCHEMENAME, PRODUCTNAME, PRODUCTID 
    FROM `edw-prod.DWH.LMS_DIMAGREEMENT`
    UNION ALL
    SELECT AGREEMENTNO, CUSTOMERID, SOURCESYSTEMID, LOANSTATUS, SCHEMENAME, PRODUCTNAME, PRODUCTID 
    FROM `edw-prod.DWH.LMSML_DIMAGREEMENT`
  ) b
  ON a.CUSTOMERID = b.CUSTOMERID 
  WHERE b.AGREEMENTNO IS NOT NULL
    AND b.LOANSTATUS IN ('A','C','ACTIVE','CLOSED')
),

dim_agg_final AS (
  SELECT * ,
    CASE 
        WHEN SOURCESYSTEMID = 21 THEN "TW"
        WHEN SOURCESYSTEMID = 20 THEN "HL"
        WHEN SOURCESYSTEMID = 23 THEN "CL"
        WHEN SOURCESYSTEMID = 25 THEN "SME"
        WHEN SOURCESYSTEMID = 24 THEN "Farm"
        WHEN SOURCESYSTEMID = 27 THEN "WRF"
        WHEN SOURCESYSTEMID = 15 THEN "ML"
        WHEN SOURCESYSTEMID = 1 THEN "Farm"
        WHEN SOURCESYSTEMID = 6 THEN "Wholesale"
        WHEN SOURCESYSTEMID = 26 THEN "Rural-LAP"
        ELSE "Non-LTF"
    END AS PRODUCT,
    CASE 
        WHEN SCHEMENAME = "SUFIN" THEN "Supply-Chain-Finance"
        WHEN (LOWER(PRODUCTNAME) LIKE '%lap%' OR LOWER(PRODUCTNAME) LIKE '%loan against property%') 
             AND SOURCESYSTEMID = 20 THEN "Loan-Against-Property"
        ELSE CASE 
            WHEN SOURCESYSTEMID = 21 THEN "TW"
            WHEN SOURCESYSTEMID = 20 THEN "HL"
            WHEN SOURCESYSTEMID = 23 THEN "CL"
            WHEN SOURCESYSTEMID = 25 THEN "SME"
            WHEN SOURCESYSTEMID = 24 THEN "Farm"
            WHEN SOURCESYSTEMID = 27 THEN "WRF"
            WHEN SOURCESYSTEMID = 15 THEN "ML"
            WHEN SOURCESYSTEMID = 1 THEN "Farm"
            WHEN SOURCESYSTEMID = 6 THEN "Wholesale"
            WHEN SOURCESYSTEMID = 26 THEN "Rural-LAP"
            ELSE "Non-LTF"
        END
    END AS Product_Final
  FROM dim_agg
),

final_data AS (
  -- Join login activity with product info and count MAU per product, per loanstatus, per month
  SELECT
    FORMAT_DATE('%Y-%m', DATE(l.CREATED_TS)) AS CREATED_MONTH,
    d.Product_Final,
    d.LOANSTATUS,
    COUNT(DISTINCT l.USER_ID) AS Monthly_Active_Users
  FROM loc_with_mobile l
  LEFT JOIN dim_agg_final d
    ON l.planet_phone_no = d.MOBILE
  GROUP BY CREATED_MONTH, d.Product_Final, d.LOANSTATUS
)

SELECT 
  CREATED_MONTH,
  Product_Final,
  LOANSTATUS,
  Monthly_Active_Users
FROM final_data
ORDER BY CREATED_MONTH, Product_Final, LOANSTATUS;

Query is running:   0%|          |

Downloading:   0%|          |

In [3]:
MAU_lob

    CREATED_MONTH          Product_Final LOANSTATUS  Monthly_Active_Users
0    2025-01       None                   None       345084
1    2025-01       CL                     A          184682
2    2025-01       CL                     C          175208
3    2025-01       Farm                   A          25163
4    2025-01       Farm                   C          19108
5    2025-01       HL                     A          11174
6    2025-01       HL                     C          4557
7    2025-01       Loan-Against-Property  A          2299
8    2025-01       Loan-Against-Property  C          910
9    2025-01       ML                     A          90920
10   2025-01       ML                     C          129424
11   2025-01       Rural-LAP              A          452
12   2025-01       Rural-LAP              C          51
13   2025-01       SME                    A          6647
14   2025-01       SME                    C          3138
15   2025-01       TW                     A          244638
16   2025-01       TW                     C          513760
17   2025-01       WRF                    A          14
18   2025-01       WRF                    C          40
19   2025-02       None                   None       247151
20   2025-02       CL                     A          176987
21   2025-02       CL                     C          163521
22   2025-02       Farm                   A          21686
23   2025-02       Farm                   C          15646
24   2025-02       HL                     A          11064
25   2025-02       HL                     C          4297
26   2025-02       Loan-Against-Property  A          2313
27   2025-02       Loan-Against-Property  C          868
28   2025-02       ML                     A          85395
29   2025-02       ML                     C          118725
30   2025-02       Rural-LAP              A          414
31   2025-02       Rural-LAP              C          53
32   2025-02       SME                    A          6765
33   2025-02       SME                    C          3087
34   2025-02       TW                     A          255106
35   2025-02       TW                     C          481079
36   2025-02       WRF                    A          13
37   2025-02       WRF                    C          40
38   2025-03       None                   None       261759
39   2025-03       CL                     A          183936
40   2025-03       CL                     C          163865
41   2025-03       Farm                   A          20946
42   2025-03       Farm                   C          15132
43   2025-03       HL                     A          10949
44   2025-03       HL                     C          4247
45   2025-03       Loan-Against-Property  A          2414
46   2025-03       Loan-Against-Property  C          894
47   2025-03       ML                     A          83372
48   2025-03       ML                     C          109818
49   2025-03       Rural-LAP              A          494
50   2025-03       Rural-LAP              C          45
51   2025-03       SME                    A          7371
52   2025-03       SME                    C          3199
53   2025-03       TW                     A          298447
54   2025-03       TW                     C          489476
55   2025-03       WRF                    A          13
56   2025-03       WRF                    C          43
57   2025-04       None                   None       240923
58   2025-04       CL                     A          180984
59   2025-04       CL                     C          156745
60   2025-04       Farm                   A          20791
61   2025-04       Farm                   C          13687
62   2025-04       HL                     A          12099
63   2025-04       HL                     C          4529
64   2025-04       Loan-Against-Property  A          2521
65   2025-04       Loan-Against-Property  C          888
66   2025-04       ML                     A          82269
67   2025-04       ML                     C          106057
68   2025-04       Rural-LAP              A          544
69   2025-04       Rural-LAP              C          58
70   2025-04       SME                    A          7616
71   2025-04       SME                    C          3155
72   2025-04       TW                     A          308485
73   2025-04       TW                     C          463342
74   2025-04       WRF                    A          18
75   2025-04       WRF                    C          45
76   2025-05       None                   None       231543
77   2025-05       CL                     A          186169
78   2025-05       CL                     C          156596
79   2025-05       Farm                   A          24375
80   2025-05       Farm                   C          15845
81   2025-05       HL                     A          12022
82   2025-05       HL                     C          4409
83   2025-05       Loan-Against-Property  A          2692
84   2025-05       Loan-Against-Property  C          873
85   2025-05       ML                     A          83828
86   2025-05       ML                     C          104887
87   2025-05       Rural-LAP              A          670
88   2025-05       Rural-LAP              C          62
89   2025-05       SME                    A          8732
90   2025-05       SME                    C          3540
91   2025-05       TW                     A          329535
92   2025-05       TW                     C          460794
93   2025-05       WRF                    A          21
94   2025-05       WRF                    C          57
95   2025-06       None                   None       240117
96   2025-06       CL                     A          192674
97   2025-06       CL                     C          155354
98   2025-06       Farm                   A          27434
99   2025-06       Farm                   C          16831
100  2025-06       HL                     A          15342
101  2025-06       HL                     C          5140
102  2025-06       Loan-Against-Property  A          3139
103  2025-06       Loan-Against-Property  C          967
104  2025-06       ML                     A          90479
105  2025-06       ML                     C          108075
106  2025-06       Rural-LAP              A          831
107  2025-06       Rural-LAP              C          80
108  2025-06       SME                    A          8628
109  2025-06       SME                    C          3408
110  2025-06       TW                     A          365441
111  2025-06       TW                     C          455830
112  2025-06       WRF                    A          13
113  2025-06       WRF                    C          52
114  2025-07       None                   None       247566
115  2025-07       CL                     A          200607
116  2025-07       CL                     C          155171
117  2025-07       Farm                   A          28059
118  2025-07       Farm                   C          16808
119  2025-07       HL                     A          13996
120  2025-07       HL                     C          4567
121  2025-07       Loan-Against-Property  A          3032
122  2025-07       Loan-Against-Property  C          894
123  2025-07       ML                     A          98003
124  2025-07       ML                     C          113120
125  2025-07       Rural-LAP              A          961
126  2025-07       Rural-LAP              C          89
127  2025-07       SME                    A          8674
128  2025-07       SME                    C          3224
129  2025-07       TW                     A          388000
130  2025-07       TW                     C          451995
131  2025-07       WRF                    A          21
132  2025-07       WRF                    C          64
133  2025-08       None                   None       241497
134  2025-08       CL                     A          177315
135  2025-08       CL                     C          133085
136  2025-08       Farm                   A          30212
137  2025-08       Farm                   C          17433
138  2025-08       HL                     A          10887
139  2025-08       HL                     C          3609
140  2025-08       Loan-Against-Property  A          2687
141  2025-08       Loan-Against-Property  C          759
142  2025-08       ML                     A          93072
143  2025-08       ML                     C          104114
144  2025-08       Rural-LAP              A          952
145  2025-08       Rural-LAP              C          82
146  2025-08       SME                    A          7915
147  2025-08       SME                    C          2716
148  2025-08       TW                     A          371085
149  2025-08       TW                     C          390413
150  2025-08       WRF                    A          25
151  2025-08       WRF                    C          64
152  2025-09       None                   None       252505
153  2025-09       CL                     A          164295
154  2025-09       CL                     C          116294
155  2025-09       Farm                   A          28310
156  2025-09       Farm                   C          15662
157  2025-09       HL                     A          11393
158  2025-09       HL                     C          3580
159  2025-09       Loan-Against-Property  A          2776
160  2025-09       Loan-Against-Property  C          766
161  2025-09       ML                     A          89781
162  2025-09       ML                     C          97445
163  2025-09       Rural-LAP              A          1012
164  2025-09       Rural-LAP              C          91
165  2025-09       SME                    A          8480
166  2025-09       SME                    C          2859
167  2025-09       TW                     A          383362
168  2025-09       TW                     C          353225
169  2025-09       WRF                    A          18
170  2025-09       WRF                    C          56
171  2025-10       None                   None       265900
172  2025-10       CL                     A          168271
173  2025-10       CL                     C          113947
174  2025-10       Farm                   A          27030
175  2025-10       Farm                   C          13915
176  2025-10       HL                     A          9812
177  2025-10       HL                     C          2807
178  2025-10       Loan-Against-Property  A          2578
179  2025-10       Loan-Against-Property  C          669
180  2025-10       ML                     A          88528
181  2025-10       ML                     C          94001
182  2025-10       Rural-LAP              A          1169
183  2025-10       Rural-LAP              C          79
184  2025-10       SME                    A          8852
185  2025-10       SME                    C          2760
186  2025-10       TW                     A          469396
187  2025-10       TW                     C          345160
188  2025-10       WRF                    A          23
189  2025-10       WRF                    C          57
190  2025-11       None                   None       221170
191  2025-11       CL                     A          161533
192  2025-11       CL                     C          102640
193  2025-11       Farm                   A          26535
194  2025-11       Farm                   C          12632
195  2025-11       HL                     A          9674
196  2025-11       HL                     C          2688
197  2025-11       Loan-Against-Property  A          2555
198  2025-11       Loan-Against-Property  C          600
199  2025-11       ML                     A          86346
200  2025-11       ML                     C          87100
201  2025-11       Non-LTF                A          1
202  2025-11       Rural-LAP              A          1183
203  2025-11       Rural-LAP              C          107
204  2025-11       SME                    A          8525
205  2025-11       SME                    C          2669
206  2025-11       TW                     A          415988
207  2025-11       TW                     C          311338
208  2025-11       WRF                    A          22
209  2025-11       WRF                    C          39
210  2025-12       None                   None       256251
211  2025-12       CL                     A          164077
212  2025-12       CL                     C          98524
213  2025-12       Farm                   A          30848
214  2025-12       Farm                   C          14360
215  2025-12       HL                     A          10997
216  2025-12       HL                     C          2794
217  2025-12       Loan-Against-Property  A          2703
218  2025-12       Loan-Against-Property  C          642
219  2025-12       ML                     A          90106
220  2025-12       ML                     C          88171
221  2025-12       Non-LTF                A          2
222  2025-12       Rural-LAP              A          1278
223  2025-12       Rural-LAP              C          96
224  2025-12       SME                    A          8317
225  2025-12       SME                    C          2520
226  2025-12       TW                     A          425274
227  2025-12       TW                     C          297191
228  2025-12       WRF                    A          22
229  2025-12       WRF                    C          38
230  2026-01       None                   None       288575
231  2026-01       CL                     A          182225
232  2026-01       CL                     C          108175
233  2026-01       Farm                   A          33760
234  2026-01       Farm                   C          15207
235  2026-01       HL                     A          13062
236  2026-01       HL                     C          2945
237  2026-01       Loan-Against-Property  A          3129
238  2026-01       Loan-Against-Property  C          669
239  2026-01       ML                     A          101512
240  2026-01       ML                     C          98743
241  2026-01       Non-LTF                A          6
242  2026-01       Rural-LAP              A          1394
243  2026-01       Rural-LAP              C          107
244  2026-01       SME                    A          9908
245  2026-01       SME                    C          2884
246  2026-01       TW                     A          482433
247  2026-01       TW                     C          310080
248  2026-01       WRF                    A          40
249  2026-01       WRF                    C          56
250  2026-02       None                   None       260190
251  2026-02       CL                     A          173729
252  2026-02       CL                     C          92244
253  2026-02       Farm                   A          27254
254  2026-02       Farm                   C          11627
255  2026-02       HL                     A          12024
256  2026-02       HL                     C          2556
257  2026-02       Loan-Against-Property  A          3077
258  2026-02       Loan-Against-Property  C          574
259  2026-02       ML                     A          99754
260  2026-02       ML                     C          89832
261  2026-02       Non-LTF                A          5
262  2026-02       Rural-LAP              A          1468
263  2026-02       Rural-LAP              C          86
264  2026-02       SME                    A          10871
265  2026-02       SME                    C          3194
266  2026-02       TW                     A          463779
267  2026-02       TW                     C          265205
268  2026-02       WRF                    A          32
269  2026-02       WRF                    C          48
270  2026-03       None                   None       225482
271  2026-03       CL                     A          189301
272  2026-03       CL                     C          91915
273  2026-03       Farm                   A          28310
274  2026-03       Farm                   C          11830
275  2026-03       HL                     A          13945
276  2026-03       HL                     C          2637
277  2026-03       Loan-Against-Property  A          3725
278  2026-03       Loan-Against-Property  C          591
279  2026-03       ML                     A          101097
280  2026-03       ML                     C          87913
281  2026-03       Non-LTF                A          2
282  2026-03       Rural-LAP              A          1596
283  2026-03       Rural-LAP              C          79
284  2026-03       SME                    A          12241
285  2026-03       SME                    C          3330
286  2026-03       TW                     A          517342
287  2026-03       TW                     C          262970
288  2026-03       WRF                    A          39
289  2026-03       WRF                    C          60
290  2026-04       None                   None       217123
291  2026-04       CL                     A          176941
292  2026-04       CL                     C          80102
293  2026-04       Farm                   A          28000
294  2026-04       Farm                   C          10755
295  2026-04       HL                     A          11722
296  2026-04       HL                     C          1845
297  2026-04       Loan-Against-Property  A          3179
298  2026-04       Loan-Against-Property  C          474
299  2026-04       ML                     A          96664
300  2026-04       ML                     C          80927
301  2026-04       Non-LTF                A          2
302  2026-04       Rural-LAP              A          1676
303  2026-04       Rural-LAP              C          54
304  2026-04       SME                    A          11402
305  2026-04       SME                    C          2897
306  2026-04       TW                     A          513958
307  2026-04       TW                     C          230675
308  2026-04       WRF                    A          50
309  2026-04       WRF                    C          61
310  2026-05       None                   None       99026
311  2026-05       CL                     A          132619
312  2026-05       CL                     C          51363
313  2026-05       Farm                   A          20509
314  2026-05       Farm                   C          6448
315  2026-05       HL                     A          7695
316  2026-05       HL                     C          1091
317  2026-05       Loan-Against-Property  A          2205
318  2026-05       Loan-Against-Property  C          249
319  2026-05       ML                     A          84535
320  2026-05       ML                     C          63150
321  2026-05       Rural-LAP              A          1348
322  2026-05       Rural-LAP              C          23
323  2026-05       SME                    A          7214
324  2026-05       SME                    C          1640
325  2026-05       TW                     A          381113
326  2026-05       TW                     C          142061
327  2026-05       WRF                    A          22
328  2026-05       WRF                    C          19

In [4]:
MAU_lob[MAU_lob['CREATED_MONTH']=="2025-08"]

    CREATED_MONTH          Product_Final LOANSTATUS  Monthly_Active_Users
133  2025-08       None                   None       241497
134  2025-08       CL                     A          177315
135  2025-08       CL                     C          133085
136  2025-08       Farm                   A          30212
137  2025-08       Farm                   C          17433
138  2025-08       HL                     A          10887
139  2025-08       HL                     C          3609
140  2025-08       Loan-Against-Property  A          2687
141  2025-08       Loan-Against-Property  C          759
142  2025-08       ML                     A          93072
143  2025-08       ML                     C          104114
144  2025-08       Rural-LAP              A          952
145  2025-08       Rural-LAP              C          82
146  2025-08       SME                    A          7915
147  2025-08       SME                    C          2716
148  2025-08       TW                     A          371085
149  2025-08       TW                     C          390413
150  2025-08       WRF                    A          25
151  2025-08       WRF                    C          64

In [5]:
MAU_lob['Product_Final'] = MAU_lob['Product_Final'].fillna("New Customer")

In [6]:
MAU_lob_agg = (
    MAU_lob.groupby(["CREATED_MONTH", "Product_Final"], as_index=False)
           .agg({"Monthly_Active_Users": "sum"})
)

pivot_df = MAU_lob_agg.pivot(
    index="CREATED_MONTH",
    columns="Product_Final",
    values="Monthly_Active_Users",
).reset_index()

pivot_df

Product_Final,CREATED_MONTH,CL,Farm,HL,Loan-Against-Property,ML,New Customer,Non-LTF,Rural-LAP,SME,TW,WRF
0,2025-01,359890,44271,15731,3209,220344,345084,<NA>,503,9785,758398,54
1,2025-02,340508,37332,15361,3181,204120,247151,<NA>,467,9852,736185,53
2,2025-03,347801,36078,15196,3308,193190,261759,<NA>,539,10570,787923,56
3,2025-04,337729,34478,16628,3409,188326,240923,<NA>,602,10771,771827,63
4,2025-05,342765,40220,16431,3565,188715,231543,<NA>,732,12272,790329,78
5,2025-06,348028,44265,20482,4106,198554,240117,<NA>,911,12036,821271,65
6,2025-07,355778,44867,18563,3926,211123,247566,<NA>,1050,11898,839995,85
7,2025-08,310400,47645,14496,3446,197186,241497,<NA>,1034,10631,761498,89
8,2025-09,280589,43972,14973,3542,187226,252505,<NA>,1103,11339,736587,74
9,2025-10,282218,40945,12619,3247,182529,265900,<NA>,1248,11612,814556,80
10,2025-11,264173,39167,12362,3155,173446,221170,1,1290,11194,727326,61
11,2025-12,262601,45208,13791,3345,178277,256251,2,1374,10837,722465,60
12,2026-01,290400,48967,16007,3798,200255,288575,6,1501,12792,792513,96
13,2026-02,265973,38881,14580,3651,189586,260190,5,1554,14065,728984,80
14,2026-03,281216,40140,16582,4316,189010,225482,2,1675,15571,780312,99
15,2026-04,257043,38755,13567,3653,177591,217123,2,1730,14299,744633,111
16,2026-05,183982,26957,8786,2454,147685,99026,<NA>,1371,8854,523174,41

In [7]:
MAU_lob_apr26 = MAU_lob[(MAU_lob['CREATED_MONTH']=="2026-04")|(MAU_lob['CREATED_MONTH']=="2026-05")]
MAU_lob_agg = (
    MAU_lob_apr26.groupby(["CREATED_MONTH", "Product_Final"], as_index=False)
           .agg({"Monthly_Active_Users": "sum"})
)

pivot_df = MAU_lob_agg.pivot(
    index="CREATED_MONTH",
    columns="Product_Final",
    values="Monthly_Active_Users",
).reset_index()

pivot_df

Product_Final,CREATED_MONTH,CL,Farm,HL,Loan-Against-Property,ML,New Customer,Non-LTF,Rural-LAP,SME,TW,WRF
0,2026-04,257043,38755,13567,3653,177591,217123,2,1730,14299,744633,111
1,2026-05,183982,26957,8786,2454,147685,99026,<NA>,1371,8854,523174,41

In [1]:
MAU_lob.pivot(
    index=['CREATED_MONTH',],
    columns=['Product_Final','LOANSTATUS'],
    values='Monthly_Active_Users'
)

NameError: name 'MAU_lob' is not defined

# New Customer

In [2]:
%%bigquery new_customer
WITH user_mapping AS (
  SELECT PHONE_NO AS planet_phone_no, USER_CREATION_ID AS USER_ID
  FROM `dataeng-datalake-prod.D2C.D2C_USER_REG_LOGIN`
  UNION ALL
  SELECT USER_PHNO1 AS planet_phone_no, USER_ID
  FROM `edw-prod.DWH_MART.D2C_TB_ASMI_USER`
),

dim_agg AS (
  SELECT 
    b.AGREEMENTNO,
    a.CUSTOMERID,
    a.DOB,
    a.MOBILE,
    b.SOURCESYSTEMID,
    b.LOANSTATUS,
    b.SCHEMENAME,
    b.PRODUCTNAME,
    a.UCID,
    b.PRODUCTID
  FROM (
    SELECT CUSTOMERID, DOB, MOBILE, UCID
    FROM `edw-prod.DWH.LMS_DIMCUSTOMER`
  ) a
  LEFT JOIN (
    SELECT AGREEMENTNO, CUSTOMERID, SOURCESYSTEMID, LOANSTATUS, SCHEMENAME, PRODUCTNAME, PRODUCTID 
    FROM `edw-prod.DWH.LMSFR_DIMAGREEMENT`
    UNION ALL
    SELECT AGREEMENTNO, CUSTOMERID, SOURCESYSTEMID, LOANSTATUS, SCHEMENAME, PRODUCTNAME, PRODUCTID 
    FROM `edw-prod.DWH.LMS_DIMAGREEMENT`
    UNION ALL
    SELECT AGREEMENTNO, CUSTOMERID, SOURCESYSTEMID, LOANSTATUS, SCHEMENAME, PRODUCTNAME, PRODUCTID 
    FROM `edw-prod.DWH.LMSML_DIMAGREEMENT`
  ) b
  ON a.CUSTOMERID = b.CUSTOMERID 
  WHERE b.AGREEMENTNO IS NOT NULL
    AND b.LOANSTATUS IN ('A','C','ACTIVE','CLOSED')
),

dim_agg_final AS (
  SELECT * ,
    CASE 
        WHEN SOURCESYSTEMID = 21 THEN "TW"
        WHEN SOURCESYSTEMID = 20 THEN "HL"
        WHEN SOURCESYSTEMID = 23 THEN "CL"
        WHEN SOURCESYSTEMID = 25 THEN "SME"
        WHEN SOURCESYSTEMID = 24 THEN "Farm"
        WHEN SOURCESYSTEMID = 27 THEN "WRF"
        WHEN SOURCESYSTEMID = 15 THEN "ML"
        WHEN SOURCESYSTEMID = 1 THEN "Farm"
        WHEN SOURCESYSTEMID = 6 THEN "Wholesale"
        WHEN SOURCESYSTEMID = 26 THEN "Rural-LAP"
        ELSE "Non-LTF"
    END AS PRODUCT,
    CASE 
        WHEN SCHEMENAME = "SUFIN" THEN "Supply-Chain-Finance"
        WHEN (LOWER(PRODUCTNAME) LIKE '%lap%' OR LOWER(PRODUCTNAME) LIKE '%loan against property%') 
             AND SOURCESYSTEMID = 20 THEN "Loan-Against-Property"
        ELSE CASE 
            WHEN SOURCESYSTEMID = 21 THEN "TW"
            WHEN SOURCESYSTEMID = 20 THEN "HL"
            WHEN SOURCESYSTEMID = 23 THEN "CL"
            WHEN SOURCESYSTEMID = 25 THEN "SME"
            WHEN SOURCESYSTEMID = 24 THEN "Farm"
            WHEN SOURCESYSTEMID = 27 THEN "WRF"
            WHEN SOURCESYSTEMID = 15 THEN "ML"
            WHEN SOURCESYSTEMID = 1 THEN "Farm"
            WHEN SOURCESYSTEMID = 6 THEN "Wholesale"
            WHEN SOURCESYSTEMID = 26 THEN "Rural-LAP"
            ELSE "Non-LTF"
        END
    END AS Product_Final
  FROM dim_agg
),

-- Join Planet users to Agreement data
mapped AS (
  SELECT 
    u.planet_phone_no,
    u.USER_ID,
    d.CUSTOMERID,
    d.AGREEMENTNO,
    d.LOANSTATUS,
    d.Product_Final
  FROM user_mapping u
  LEFT JOIN dim_agg_final d
    ON SAFE_CAST(u.planet_phone_no AS STRING) = SAFE_CAST(d.MOBILE AS STRING)
)

-- Final aggregation
SELECT
  Product_Final,
  LOANSTATUS,
  COUNT(DISTINCT CUSTOMERID) AS customer_count,
  COUNT(DISTINCT CASE WHEN AGREEMENTNO IS NULL THEN USER_ID END) AS planet_only_userid_count,
  COUNT(DISTINCT CASE WHEN AGREEMENTNO IS NULL THEN planet_phone_no END) AS planet_only_phone_count
FROM mapped
GROUP BY Product_Final, LOANSTATUS
ORDER BY Product_Final, LOANSTATUS;

Query is running:   0%|          |

Downloading:   0%|          |

In [3]:
new_customer

,Product_Final,LOANSTATUS,customer_count,planet_only_userid_count,planet_only_phone_count
0,None,None,0,6392842,6380164
1,CL,A,556199,0,0
2,CL,C,419652,0,0
3,Farm,A,165613,0,0
4,Farm,C,157872,0,0
5,HL,A,48098,0,0
6,HL,C,15007,0,0
7,Loan-Against-Property,A,9596,0,0
8,Loan-Against-Property,C,3777,0,0
9,ML,A,981834,0,0
10,ML,C,1545590,0,0
11,Rural-LAP,A,3187,0,0
12,Rural-LAP,C,96,0,0
13,SME,A,28524,0,0
14,SME,C,5575,0,0
15,Supply-Chain-Finance,A,126,0,0
16,Supply-Chain-Finance,C,114,0,0
17,TW,A,1468304,0,0
18,TW,C,2048673,0,0
19,WRF,A,1127,0,0
20,WRF,C,3337,0,0

# DAU

In [5]:
%%bigquery loc_with_mobile_flagged
WITH user_mapping AS (
  SELECT 
    PHONE_NO AS planet_phone_no, 
    USER_CREATION_ID AS USER_ID
  FROM `dataeng-datalake-prod.D2C.D2C_USER_REG_LOGIN`
  
  UNION ALL
  
  SELECT 
    USER_PHNO1 AS planet_phone_no, 
    USER_ID
  FROM `edw-prod.DWH_MART.D2C_TB_ASMI_USER`
),

loc_with_mobile AS (
  -- All login events with mobile mapping
  SELECT 
    l.USER_ID,
    DATE(l.CREATED_TS) AS LOGIN_DATE,
    m.planet_phone_no
  FROM (
    SELECT USER_ID, CREATED_TS
    FROM `edw-prod.DWH_MART.D2C_TB_USER_LOC_TRACKING`
    WHERE CREATED_TS >= '2025-06-01'
      AND CREATED_TS < '2025-12-01'
    
    UNION ALL
    
    SELECT USER_CREATION_ID AS USER_ID, LOGIN_DATE AS CREATED_TS
    FROM `dataeng-datalake-prod.D2C.D2C_USER_LOGIN_TRACKER`
    WHERE LOGIN_DATE >= '2025-06-01'
      AND LOGIN_DATE < '2025-12-01'
  ) l
  LEFT JOIN user_mapping m
    ON l.USER_ID = m.USER_ID
),

dim_agg AS (
  SELECT 
    b.AGREEMENTNO,
    a.MOBILE
  FROM `edw-prod.DWH.LMS_DIMCUSTOMER` a
  LEFT JOIN (
    SELECT AGREEMENTNO, CUSTOMERID 
    FROM `edw-prod.DWH.LMSFR_DIMAGREEMENT`
    UNION ALL
    SELECT AGREEMENTNO, CUSTOMERID 
    FROM `edw-prod.DWH.LMS_DIMAGREEMENT`
    UNION ALL
    SELECT AGREEMENTNO, CUSTOMERID 
    FROM `edw-prod.DWH.LMSML_DIMAGREEMENT`
  ) b
  ON a.CUSTOMERID = b.CUSTOMERID 
  WHERE b.AGREEMENTNO IS NOT NULL
)

SELECT 
  l.USER_ID,
  l.LOGIN_DATE,
  l.planet_phone_no,
  CASE 
    WHEN u.USER_ID IS NOT NULL THEN 1 
    ELSE 0 
  END AS Planet_REG,
  CASE 
    WHEN d.MOBILE IS NOT NULL THEN 1 
    ELSE 0 
  END AS Existing_Customer
FROM (
  SELECT DISTINCT USER_ID, LOGIN_DATE, planet_phone_no
  FROM loc_with_mobile
) l
LEFT JOIN user_mapping u
  ON l.USER_ID = u.USER_ID
LEFT JOIN dim_agg d
  ON l.planet_phone_no = d.MOBILE
ORDER BY l.LOGIN_DATE, l.USER_ID;

Query is running:   0%|          |

Downloading:   0%|          |

In [6]:
loc_with_mobile_flagged.sample(3)

,USER_ID,LOGIN_DATE,planet_phone_no,Planet_REG,Existing_Customer
3029261,user20221217153735427,2025-09-14,9851789646,1,1
5091761,user20230113095713025,2025-09-29,8273421896,1,1
3176835,user20230712174510390,2025-09-15,9353440134,1,1

In [9]:
loc_with_mobile_flagged.Planet_REG.value_counts()

Planet_REG
1    5366203
0    328
Name: count, dtype: Int64

In [11]:
pd.pivot_table(loc_with_mobile_flagged,index='LOGIN_DATE',aggfunc={'planet_phone_no':'nunique','Existing_Customer':'count'})

            Existing_Customer  planet_phone_no
LOGIN_DATE
2025-09-01  214120             85882
2025-09-02  293326             116631
2025-09-03  521123             207272
2025-09-04  304892             120845
2025-09-05  240942             96409
2025-09-06  201270             79468
2025-09-07  167045             65378
2025-09-08  218382             85087
2025-09-09  192972             75443
2025-09-10  187385             73475
2025-09-11  169365             66973
2025-09-12  153217             61479
2025-09-13  140185             57135
2025-09-14  99668              40514
2025-09-15  167625             66981
2025-09-16  143100             58192
2025-09-17  131644             53812
2025-09-18  135574             55232
2025-09-19  129536             53249
2025-09-20  118809             48880
2025-09-21  108030             45520
2025-09-22  148920             63831
2025-09-23  143869             62098
2025-09-24  149637             65158
2025-09-25  146907             63761
2025-09-26  141370             61705
2025-09-27  132261             57916
2025-09-28  139945             61422
2025-09-29  154506             67294
2025-09-30  170906             74257

In [1]:
import pandas as pd
ss = pd.read_csv('gs://ltfs-analytics-prod-bucket/Analytics_Ops/Marketing Analytics/PDM/Output/general_December25_lot1.csv')
ss.shape,ss.Agreement_no.

/var/tmp/ipykernel_78562/4034061396.py:2: DtypeWarning: Columns (1,2,4,6,21,24,36,38,40,41,42,43,50) have mixed types. Specify dtype option on import or set low_memory=False.
  ss = pd.read_csv('gs://ltfs-analytics-prod-bucket/Analytics_Ops/Marketing Analytics/PDM/Output/general_December25_lot1.csv')

(33976, 65)

In [2]:
ss.sample(3)

,Agreement_no,Allocation_Date,Asset_Make,Bounce_Count,Bounce_Type,Bounce_Charge_Due,Bounce_Date,Bounce_Last_1_Month,Branchname,Bureau_Flag,...,EMI,STATE_y,LOANSTATUS,SUB_SBU,DISBURSALDATE,DOB,base_date,age,Reg_Date,segments
23835,C022062401030416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PATIALA-CHOTI BARADARI-93,crif,...,6668.0,PUNJAB,A,CL,2022-06-25,1990-03-14,2025-11-26,35,2023-01-26,General
25972,C02511154059485377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SIKAR-ROADWAYS BUS DEPO-69,crif,...,24467.0,RAJASTHAN,A,CL,2025-11-18,1988-09-28,2025-11-26,37,NaN,General
31196,C02405140895430340,NaN,NaN,NaN,NaN,NaN,NaN,0.0,BANGALORE-LALBAGH ROAD-LTF-13,crif,...,7479.0,KARNATAKA,A,CL,2024-05-14,1975-01-17,2025-11-26,50,2023-04-12,General

In [12]:
%%bigquery non_login_base
WITH
PLANET_REG AS (
    SELECT 
        PHONE_NO AS MOBILE, 
        USER_CREATION_ID AS USER_ID, 
        REGISTRATION_DATE AS Planet_Reg_Date
    FROM `dataeng-datalake-prod.D2C.D2C_USER_REG_LOGIN`

    UNION ALL

    SELECT 
        USER_PHNO1 AS MOBILE, 
        USER_ID,
        CREATE_TS AS Planet_Reg_Date
    FROM `edw-prod.DWH_MART.D2C_TB_ASMI_USER`
),

loc_with_mobile AS (
    SELECT 
        l.USER_ID,
        l.CREATED_TS,
        m.MOBILE AS MOBILE
    FROM (
        SELECT 
            USER_ID, 
            CREATED_TS
        FROM `edw-prod.DWH_MART.D2C_TB_USER_LOC_TRACKING`
        WHERE CREATED_TS >= '2025-11-01'
          AND CREATED_TS < '2025-11-27'

        UNION ALL

        SELECT 
            USER_CREATION_ID AS USER_ID, 
            LOGIN_DATE AS CREATED_TS
        FROM `dataeng-datalake-prod.D2C.D2C_USER_LOGIN_TRACKER`
        WHERE LOGIN_DATE >= '2025-11-01'
          AND LOGIN_DATE < '2025-11-27'
    ) l
    LEFT JOIN PLANET_REG m
        ON l.USER_ID = m.USER_ID
),

final_base AS (
    SELECT 
        pr.*,
        CASE WHEN lw.MOBILE IS NOT NULL THEN 1 ELSE 0 END AS Login_Flag,
        lw.CREATED_TS AS Last_Login_Time
    FROM PLANET_REG pr
    LEFT JOIN loc_with_mobile lw
        ON pr.MOBILE = lw.MOBILE
),

-- Deduplication: Keep latest record per MOBILE
ranked AS (
    SELECT 
        *,
        ROW_NUMBER() OVER (PARTITION BY MOBILE ORDER BY Last_Login_Time DESC NULLS LAST) AS rn
    FROM final_base
)

SELECT *
FROM ranked
WHERE rn = 1        -- keep latest record only
ORDER BY Last_Login_Time DESC;

Query is running:   0%|          |

Downloading:   0%|          |

In [13]:
non_login_base.shape

(12547297, 6)

In [14]:
non_login_base.shape,non_login_base.MOBILE.nunique()

((12547297, 6), 12547296)

In [15]:
non_login_base.sample(2)

,MOBILE,USER_ID,Planet_Reg_Date,Login_Flag,Last_Login_Time,rn
6571018,7381387560,user20221116214730332,2022-11-16 21:48:22.867,0,NaT,1
509755,6385730410,user20240715225112700,2024-07-15 22:52:44.410,1,2025-11-13 11:59:21.467,1

In [16]:
non_login_base.Login_Flag.value_counts()

Login_Flag
0    11485739
1     1061558
Name: count, dtype: Int64

## Disbursal Date

In [1]:
%%bigquery planet_portfolio_penetration

WITH DATE_FILTER AS (
  SELECT 
    DATE('2025-12-01') AS START_DATE,   -- 🔴 Change Start Date Here
    DATE('2026-02-28') AS END_DATE      -- 🔴 Change End Date Here
),

DIM_AGG AS (
    SELECT 
        b.AGREEMENTNO,
        a.CUSTOMERID,
        a.DOB,
        a.MOBILE,
        a.CITY,
        b.SOURCESYSTEMID,
        b.LOANSTATUS,
        b.STATE,
        b.DISBURSALDATE,
        b.DISBURSALAMOUNT,
        b.SCHEMENAME,
        b.PRODUCTNAME,
        a.UCID,
        b.PRODUCTID,
        b.NPASTAGEID
    FROM `edw-prod.DWH.LMS_DIMCUSTOMER` a
    LEFT JOIN (
        SELECT AGREEMENTNO, CUSTOMERID, SOURCESYSTEMID, LOANSTATUS, DISBURSALDATE, 
               DISBURSALAMOUNT, SCHEMENAME, PRODUCTNAME, PRODUCTID, STATE, NPASTAGEID 
        FROM `edw-prod.DWH.LMSFR_DIMAGREEMENT`
        UNION ALL
        SELECT AGREEMENTNO, CUSTOMERID, SOURCESYSTEMID, LOANSTATUS, DISBURSALDATE, 
               DISBURSALAMOUNT, SCHEMENAME, PRODUCTNAME, PRODUCTID, STATE, NPASTAGEID 
        FROM `edw-prod.DWH.LMS_DIMAGREEMENT`
        UNION ALL
        SELECT AGREEMENTNO, CUSTOMERID, SOURCESYSTEMID, LOANSTATUS, DISBURSALDATE, 
               DISBURSALAMOUNT, SCHEMENAME, PRODUCTNAME, PRODUCTID, STATE, NPASTAGEID 
        FROM `edw-prod.DWH.LMSML_DIMAGREEMENT`
    ) b
    ON a.CUSTOMERID = b.CUSTOMERID
    CROSS JOIN DATE_FILTER d
    WHERE b.AGREEMENTNO IS NOT NULL
      AND b.LOANSTATUS IN ('A', 'C', 'ACTIVE', 'CLOSED')
      AND DATE(b.DISBURSALDATE) BETWEEN d.START_DATE AND d.END_DATE
),

DIM_AGG_FINAL AS (
    SELECT *,
        CASE 
            WHEN SOURCESYSTEMID = 21 THEN "TW"
            WHEN SOURCESYSTEMID = 20 THEN "HL"
            WHEN SOURCESYSTEMID = 23 THEN "CL"
            WHEN SOURCESYSTEMID = 25 THEN "SME"
            WHEN SOURCESYSTEMID = 24 THEN "Farm"
            WHEN SOURCESYSTEMID = 27 THEN "WRF"
            WHEN SOURCESYSTEMID = 15 THEN "ML"
            WHEN SOURCESYSTEMID = 1 THEN "Farm"
            WHEN SOURCESYSTEMID = 6 THEN "Wholesale"
            WHEN SOURCESYSTEMID = 26 THEN "Rural-LAP"
            ELSE "Non-LTF"
        END AS PRODUCT,
        CASE 
            WHEN SCHEMENAME = "SUFIN" THEN "Supply-Chain-Finance"
            WHEN LOWER(PRODUCTNAME) LIKE '%lap%' 
                 OR LOWER(PRODUCTNAME) LIKE '%loan against property%' 
                    AND SOURCESYSTEMID = 20 THEN "Loan-Against-Property"
            ELSE 
                CASE 
                    WHEN SOURCESYSTEMID = 21 THEN "TW"
                    WHEN SOURCESYSTEMID = 20 THEN "HL"
                    WHEN SOURCESYSTEMID = 23 THEN "CL"
                    WHEN SOURCESYSTEMID = 25 THEN "SME"
                    WHEN SOURCESYSTEMID = 24 THEN "Farm"
                    WHEN SOURCESYSTEMID = 27 THEN "WRF"
                    WHEN SOURCESYSTEMID = 15 THEN "ML"
                    WHEN SOURCESYSTEMID = 1 THEN "Farm"
                    WHEN SOURCESYSTEMID = 6 THEN "Wholesale"
                    WHEN SOURCESYSTEMID = 26 THEN "Rural-LAP"
                    ELSE "Non-LTF"
                END
        END AS Product_Final
    FROM DIM_AGG
),

DIM_AGG_CHECK_FINAL AS (
    SELECT * FROM (
        SELECT *, 
               ROW_NUMBER() OVER (PARTITION BY UCID, Product_Final 
                                  ORDER BY DISBURSALDATE DESC) AS rn
        FROM DIM_AGG_FINAL
        WHERE UCID IS NOT NULL 
          AND MOBILE IS NOT NULL 
          AND MOBILE != 'None'
    ) 
    WHERE rn = 1
),

PRODUCT_DIST_FINAL AS (
    SELECT 
        FORMAT_DATE('%Y-%m', DATE(DISBURSALDATE)) AS DISB_MONTH,
        Product_Final,
        COUNT(DISTINCT UCID) AS CUSTOMER_COUNT,
        'PRODUCT' AS Source_Tag  
    FROM DIM_AGG_CHECK_FINAL
    GROUP BY DISB_MONTH, Product_Final
),

PLANET_REG AS (
    SELECT PHONE_NO AS MOBILE, USER_CREATION_ID AS USER_ID, 
           REGISTRATION_DATE AS Planet_Reg_Date
    FROM `dataeng-datalake-prod.D2C.D2C_USER_REG_LOGIN`
    UNION ALL
    SELECT USER_PHNO1 AS MOBILE, USER_ID, 
           CREATE_TS AS Planet_Reg_Date
    FROM `edw-prod.DWH_MART.D2C_TB_ASMI_USER`
),

PLANET_AGG AS (
    SELECT 
        p.MOBILE AS MOBILE_ASMI, 
        p.USER_ID, 
        p.Planet_Reg_Date, 
        d.AGREEMENTNO, 
        d.MOBILE, 
        d.UCID, 
        d.STATE, 
        d.Product_Final, 
        d.DISBURSALDATE
    FROM PLANET_REG p
    INNER JOIN DIM_AGG_CHECK_FINAL d
        ON p.MOBILE = d.MOBILE
),

PLANET_DIST_FINAL AS (
    SELECT 
        FORMAT_DATE('%Y-%m', DATE(DISBURSALDATE)) AS DISB_MONTH,
        Product_Final,
        COUNT(DISTINCT UCID) AS CUSTOMER_COUNT,
        'PLANET' AS Source_Tag  
    FROM PLANET_AGG
    GROUP BY DISB_MONTH, Product_Final
)

SELECT * FROM PRODUCT_DIST_FINAL
UNION ALL
SELECT * FROM PLANET_DIST_FINAL
ORDER BY DISB_MONTH, Product_Final, Source_Tag;

Query is running:   0%|          |

Downloading:   0%|          |

In [2]:
planet_portfolio_penetration.head()

  DISB_MONTH Product_Final  CUSTOMER_COUNT Source_Tag
0    2025-12            CL           20580     PLANET
1    2025-12            CL           40778    PRODUCT
2    2025-12          Farm            2680     PLANET
3    2025-12          Farm           10923    PRODUCT
4    2025-12            HL             844     PLANET

In [5]:
import pandas as pd
pd.pivot(planet_portfolio_penetration, index='DISB_MONTH',columns=['Product_Final','Source_Tag'],values='CUSTOMER_COUNT').fillna(0)

Product_Final     CL           Farm             HL          \
Source_Tag    PLANET PRODUCT PLANET PRODUCT PLANET PRODUCT
DISB_MONTH
2025-12        20580   40778   2680   10923    844    1263
2026-01        20575   43845   2589   11246    393     498
2026-02        16524   42143   2160   10164    570    1017

Product_Final Loan-Against-Property             ML         Non-LTF          \
Source_Tag                   PLANET PRODUCT PLANET PRODUCT  PLANET PRODUCT
DISB_MONTH
2025-12                         260     401  32833  270187       5      12
2026-01                         144     181  30617  262798       2      10
2026-02                         138     315  28652  267992       0       4

Product_Final Rural-LAP            SME             TW            WRF
Source_Tag       PLANET PRODUCT PLANET PRODUCT PLANET PRODUCT PLANET PRODUCT
DISB_MONTH
2025-12             252    1127   1203    1861  64699   64795     22      37
2026-01             232    1219   1092    1735  83279   84083     26      44
2026-02             239    1268    928    1769  70102   73861     47      92

## Latest Disbursal Planet campaign Base

In [25]:
%%bigquery customer_campaign_base



WITH user_mapping AS (
  SELECT 
      PHONE_NO AS planet_phone_no, 
      USER_CREATION_ID AS USER_ID,
      DATE(REGISTRATION_DATE) AS Planet_Reg_date
  FROM `dataeng-datalake-prod.D2C.D2C_USER_REG_LOGIN`

  UNION ALL

  SELECT 
      USER_PHNO1 AS planet_phone_no, 
      USER_ID,
      DATE(CREATE_TS) AS Planet_Reg_date
  FROM `edw-prod.DWH_MART.D2C_TB_ASMI_USER`
),

latest_login AS (
  SELECT 
      l.USER_ID,
      MAX(l.CREATED_TS) AS latest_login_date
  FROM (
      SELECT USER_ID, CREATED_TS
      FROM `edw-prod.DWH_MART.D2C_TB_USER_LOC_TRACKING`

      UNION ALL

      SELECT USER_CREATION_ID AS USER_ID, LOGIN_DATE AS CREATED_TS
      FROM `dataeng-datalake-prod.D2C.D2C_USER_LOGIN_TRACKER`
  ) l
  GROUP BY l.USER_ID
),

user_login_mobile AS (
  SELECT 
      m.planet_phone_no,
      m.USER_ID,
      m.Planet_Reg_date,
      ll.latest_login_date
  FROM user_mapping m
  LEFT JOIN latest_login ll
      ON m.USER_ID = ll.USER_ID
),

dim_agg AS (
  SELECT 
      b.AGREEMENTNO,
      a.MOBILE,
      b.DISBURSALDATE,
      b.PRODUCTNAME,
      b.SOURCESYSTEMID
  FROM `edw-prod.DWH.LMS_DIMCUSTOMER` a
  LEFT JOIN `edw-prod.DWH.LMSFR_DIMAGREEMENT` b
      ON a.CUSTOMERID = b.CUSTOMERID
  WHERE DATE(b.DISBURSALDATE) >= DATE_SUB(CURRENT_DATE(), INTERVAL 7 DAY) AND b.PRODUCTNAME NOT LIKE '%CL_Large_Partnership%'
),

product_logic AS (
  SELECT *,
      CASE 
        WHEN SOURCESYSTEMID = 21 THEN "TW"
        WHEN SOURCESYSTEMID = 20 THEN "HL"
        WHEN SOURCESYSTEMID = 23 THEN "CL"
        WHEN SOURCESYSTEMID = 25 THEN "SME"
        WHEN SOURCESYSTEMID = 24 THEN "Farm"
        WHEN SOURCESYSTEMID = 27 THEN "WRF"
        WHEN SOURCESYSTEMID = 15 THEN "ML"
        WHEN SOURCESYSTEMID = 1 THEN "Farm"
        WHEN SOURCESYSTEMID = 6 THEN "Wholesale"
        WHEN SOURCESYSTEMID = 26 THEN "Rural-LAP"
        ELSE "Non-LTF"
      END AS Product_Final
  FROM dim_agg
),

final_base AS (
  SELECT
      d.AGREEMENTNO,
      d.MOBILE,
      DATE(d.DISBURSALDATE) AS Disbursal_date,
      d.PRODUCTNAME,
      d.Product_Final,

      CASE 
          WHEN u.planet_phone_no IS NOT NULL THEN 1
          ELSE 0
      END AS Planet_Reg_flag,

      u.Planet_Reg_date,
      u.latest_login_date,

      DATE_DIFF(DATE(d.DISBURSALDATE), DATE(u.latest_login_date), DAY) AS Recency

  FROM product_logic d
  LEFT JOIN user_login_mobile u
      ON d.MOBILE = u.planet_phone_no
)

SELECT *
FROM (
  SELECT *,
         ROW_NUMBER() OVER(PARTITION BY AGREEMENTNO ORDER BY Disbursal_date DESC) AS rn
  FROM final_base
)
WHERE rn = 1

Query is running:   0%|          |

Downloading:   0%|          |

In [26]:
customer_campaign_base.sample(10)

,AGREEMENTNO,MOBILE,Disbursal_date,PRODUCTNAME,Product_Final,Planet_Reg_flag,Planet_Reg_date,latest_login_date,Recency,rn
5021,C02603031514621816,8093520590,2026-03-03,CONSUMER_LOAN,CL,1,2022-06-09,2026-02-18 14:30:57.260,13,1
680,C02603074911966680,9986653505,2026-03-07,CONSUMER_LOAN,CL,0,NaT,NaT,<NA>,1
5380,C02603052121491225,8146503257,2026-03-06,CONSUMER_LOAN,CL,1,2026-03-05,2026-03-08 10:49:12.483,-2,1
2546,C02602181342393211,9051808740,2026-03-04,CONSUMER_LOAN,CL,1,2025-08-23,2026-03-04 16:44:16.850,0,1
1598,C02603085877550529,9687032370,2026-03-08,CONSUMER_LOAN,CL,1,2023-01-06,2026-03-07 19:28:21.373,1,1
5340,F0059K610703260362,8374593089,2026-03-07,FARM-Kisan Gaurav,Farm,0,NaT,NaT,<NA>,1
5205,C02603045891407535,9679881881,2026-03-04,CONSUMER_LOAN,CL,1,2023-09-21,2023-09-21 10:37:48.000,895,1
1213,C02603020133638456,9974879185,2026-03-02,CONSUMER_LOAN,CL,1,2025-08-26,2025-08-26 19:04:36.577,188,1
4202,C02603031672488855,8001676923,2026-03-06,CONSUMER_LOAN,CL,1,2022-11-06,2026-03-06 13:03:27.177,0,1
4951,C02603085922162080,8609382003,2026-03-08,CONSUMER_LOAN,CL,1,2023-01-07,2026-03-08 13:46:40.680,0,1

In [27]:
customer_campaign_base.PRODUCTNAME.value_counts()

PRODUCTNAME
CONSUMER_LOAN        4303
FARM-Kisan Gaurav     956
BUSINESS_LOAN          83
FARMFIN_WRF            65
Name: count, dtype: int64

In [28]:
customer_campaign_base.shape,customer_campaign_base.AGREEMENTNO.nunique()

((5407, 10), 5407)

In [29]:
customer_campaign_base[customer_campaign_base['AGREEMENTNO']=='C02603082895327174']

,AGREEMENTNO,MOBILE,Disbursal_date,PRODUCTNAME,Product_Final,Planet_Reg_flag,Planet_Reg_date,latest_login_date,Recency,rn
88,C02603082895327174,9732000396,2026-03-08,CONSUMER_LOAN,CL,1,2024-03-22,2026-01-30 16:21:38.273,37,1

In [30]:
customer_campaign_base.Disbursal_date.min(), customer_campaign_base.Disbursal_date.max()

(datetime.date(2026, 3, 2), datetime.date(2026, 3, 8))

In [31]:
customer_campaign_base.to_csv('Newly_disbursed_customer.csv', index=False)